{% set name = "yfinance" %}
{% set version = "0.2.30" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/yfinance-{{ version }}.tar.gz
  sha256: 9b980cfb20beb903c4e3dee212de305f3d6fea96e5c571bf424239da974970fe

build:
  number: 0
  noarch: python
  entry_points:
    - sample=sample: main  # [win]
  script: mkdir -p /home/conda/.cache; {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6
    - appdirs >=1.4.4
    - beautifulsoup4 >=4.11.1
    - cryptography >=3.3.2
    - frozendict >=2.3.4
    - html5lib >=1.1
    - lxml >=4.9.1
    - multitasking >=0.0.7
    - numpy >=1.16.5
    - pandas >=1.3.0
    - peewee >=3.16.2
    - pytz >=2022.5
    - requests >=2.26

test:
  imports:
    - yfinance
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/ranaroussi/yfinance
  summary: Yahoo! Finance market data downloader
  license: Apache-2.0
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - jan-janssen
    - timkpaine
