{% set name = "yfinance" %}
{% set version = "0.2.18" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/yfinance-{{ version }}.tar.gz
  sha256: 3874ee22eb35563a797348d2a5a00b665c9a1c50d21287050db1c5341ecc5c1b

build:
  number: 0
  noarch: python
  entry_points:
    - sample=sample: main  # [win]
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - lxml >=4.5.1
    - multitasking >=0.0.7
    - numpy >=1.15
    - pandas >=0.24
    - python >=3.6
    - requests >=2.20
    - appdirs
    - frozendict
    - beautifulsoup4
    - html5lib

test:
  imports:
    - yfinance
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/ranaroussi/yfinance
  summary: Yahoo! Finance market data downloader
  license: Apache-2.0
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - jan-janssen
