{% set name = "yfinance" %}
{% set version = "0.2.33" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/yfinance-{{ version }}.tar.gz
  sha256: 08aeb63a927742514098698d80f4315aa92d23bc253c1f204ced6377457c3e07

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - pandas >=1.3.0
    - numpy >=1.16.5
    - requests >=2.31
    - multitasking >=0.0.7
    - lxml >=4.9.1
    - appdirs >=1.4.4
    - pytz >=2022.5
    - frozendict >=2.3.4
    - peewee >=3.16.2
    - beautifulsoup4 >=4.11.1
    - html5lib >=1.1

test:
  imports:
    - yfinance
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/ranaroussi/yfinance
  summary: Download market data from Yahoo! Finance API
  license: Apache-2.0
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - jan-janssen
    - timkpaine
